name: 'Git Diff'
description: 'Github actions to retrive a list of files changed between the current and last commit on the same branch'
inputs:
  current_sha:  # id of input
    description: 'Commit id from the current (SHA)'
    required: true
  current_ref:  # id of input
    description: 'Branch that is running'
    required: true
outputs:
  files:
    description: "list of files with space separator"
    value: ${{ steps.list-of-files.outputs.files-list }}
runs:
  using: "composite"
  steps:
    - run: echo current_sha ${{ inputs.current_sha }}. current_ref ${{ inputs.current_ref }}.
      shell: bash
    - run: git log --pretty=oneline | sed -n 2p | tr -s ' ' | cut -d ' ' -f 1
      name: debug Git Last Commit
      shell: bash
    - run: echo "LAST_COMMIT=$(git log --pretty=oneline | sed -n 2p | tr -s ' ' | cut -d ' ' -f 1)" >> $GITHUB_ENV
      name: Git Last Commit
      shell: bash
    - id: list-of-files
      run: echo "::set-output name=files-list::=$(git diff $GITHUB_SHA $LAST_COMMIT --name-only)"
      name: Get list of files
      shell: bash